package co.edu.usbcali.actividades.modelo;
// Generated 15/08/2016 09:18:31 PM by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * Actividad generated by hbm2java
 */
public class Actividad  implements java.io.Serializable {


     private Integer actiId;
     private String nombreActividad;
     private String descripcion;
     private Set<RegistroActividad> registroActividads = new HashSet<RegistroActividad>(0);

    public Actividad() {
    }

	
    public Actividad(Integer actiId, String nombreActividad, String descripcion) {
        this.actiId = actiId;
        this.nombreActividad = nombreActividad;
        this.descripcion = descripcion;
    }
    public Actividad(Integer actiId, String nombreActividad, String descripcion, Set<RegistroActividad> registroActividads) {
       this.actiId = actiId;
       this.nombreActividad = nombreActividad;
       this.descripcion = descripcion;
       this.registroActividads = registroActividads;
    }
   
    public Integer getActiId() {
        return this.actiId;
    }
    
    public void setActiId(Integer actiId) {
        this.actiId = actiId;
    }
    public String getNombreActividad() {
        return this.nombreActividad;
    }
    
    public void setNombreActividad(String nombreActividad) {
        this.nombreActividad = nombreActividad;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<RegistroActividad> getRegistroActividads() {
        return this.registroActividads;
    }
    
    public void setRegistroActividads(Set<RegistroActividad> registroActividads) {
        this.registroActividads = registroActividads;
    }




}


