package co.edu.usbcali.actividades.modelo;
// Generated 15/08/2016 09:18:31 PM by Hibernate Tools 4.0.0


import java.util.Date;

/**
 * RegistroActividad generated by hbm2java
 */
public class RegistroActividad  implements java.io.Serializable {


     private Integer regiId;
     private Actividad actividad;
     private Usuario usuario;
     private Long tiempoMin;
     private Date tiempoHoras;
     private Date fechaRegistro;
     private Date fechaCreacion;

    public RegistroActividad() {
    }

	
    public RegistroActividad(Integer regiId, Long tiempoMin, Date tiempoHoras, Date fechaRegistro, Date fechaCreacion) {
        this.regiId = regiId;
        this.tiempoMin = tiempoMin;
        this.tiempoHoras = tiempoHoras;
        this.fechaRegistro = fechaRegistro;
        this.fechaCreacion = fechaCreacion;
    }
    public RegistroActividad(Integer regiId, Actividad actividad, Usuario usuario, Long tiempoMin, Date tiempoHoras, Date fechaRegistro, Date fechaCreacion) {
       this.regiId = regiId;
       this.actividad = actividad;
       this.usuario = usuario;
       this.tiempoMin = tiempoMin;
       this.tiempoHoras = tiempoHoras;
       this.fechaRegistro = fechaRegistro;
       this.fechaCreacion = fechaCreacion;
    }
   
    public Integer getRegiId() {
        return this.regiId;
    }
    
    public void setRegiId(Integer regiId) {
        this.regiId = regiId;
    }
    public Actividad getActividad() {
        return this.actividad;
    }
    
    public void setActividad(Actividad actividad) {
        this.actividad = actividad;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Long getTiempoMin() {
        return this.tiempoMin;
    }
    
    public void setTiempoMin(Long tiempoMin) {
        this.tiempoMin = tiempoMin;
    }
    public Date getTiempoHoras() {
        return this.tiempoHoras;
    }
    
    public void setTiempoHoras(Date tiempoHoras) {
        this.tiempoHoras = tiempoHoras;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }




}


