package co.edu.usbcali.actividades.modelo;
// Generated 15/08/2016 09:18:31 PM by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer usuaId;
     private String nombreCompleto;
     private String email;
     private String password;
     private String numDocumento;
     private Set<RegistroActividad> registroActividads = new HashSet<RegistroActividad>(0);

    public Usuario() {
    }

	
    public Usuario(Integer usuaId, String nombreCompleto, String email, String password, String numDocumento) {
        this.usuaId = usuaId;
        this.nombreCompleto = nombreCompleto;
        this.email = email;
        this.password = password;
        this.numDocumento = numDocumento;
    }
    public Usuario(Integer usuaId, String nombreCompleto, String email, String password, String numDocumento, Set<RegistroActividad> registroActividads) {
       this.usuaId = usuaId;
       this.nombreCompleto = nombreCompleto;
       this.email = email;
       this.password = password;
       this.numDocumento = numDocumento;
       this.registroActividads = registroActividads;
    }
   
    public Integer getUsuaId() {
        return this.usuaId;
    }
    
    public void setUsuaId(Integer usuaId) {
        this.usuaId = usuaId;
    }
    public String getNombreCompleto() {
        return this.nombreCompleto;
    }
    
    public void setNombreCompleto(String nombreCompleto) {
        this.nombreCompleto = nombreCompleto;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getNumDocumento() {
        return this.numDocumento;
    }
    
    public void setNumDocumento(String numDocumento) {
        this.numDocumento = numDocumento;
    }
    public Set<RegistroActividad> getRegistroActividads() {
        return this.registroActividads;
    }
    
    public void setRegistroActividads(Set<RegistroActividad> registroActividads) {
        this.registroActividads = registroActividads;
    }




}


